---
- name: configuration backup
  hosts: CISCO-IOS*
  gather_facts: false
  tasks:
   - name: config backup
     ios_config:
      backup: yes
      backup_options:
       dir_path: /etc/ansible/backup/IOS
...

